ecommerce/models.py
from flask_login import UserMixin
from . import db
import logging

class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(15), unique=True, nullable=False)
    password = db.Column(db.String(12), unique=True, nullable=False)
    email = db.Column(db.String(255), nullable=False)

    def __repr__(self):
        return '<User %r>' % self.username

class Shoe(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(255), nullable=False)
    price = db.Column(db.Float, nullable=False)
    
    def __repr__(self):
        return '<Shoes %r>' % self.title

ecommerce/__init__.py
#https://flask-mail.readthedocs.io/en/latest/
#https://www.youtube.com/watch?v=48Eb8JuFuUI
from flask import Flask
from flask_mail import Mail
from flask_login import LoginManager
from flask_sqlalchemy import SQLAlchemy
import os, logging


#Set up logger
logger = logging.getLogger(__name__)
logger.setLevel(logging.DEBUG)
logging.basicConfig(filename='server.log', format='%(asctime)s:%(module)s:%(levelname)s:%(message)s')

#Variables
app = Flask(__name__)
db = SQLAlchemy()
mail = Mail()

email = open('note_email', 'r').read()
password = open('note_password', 'r').read()

#Factory
def create_app():
    from . import models, views, auth, store
    #Configurations
    app.config['SECRET_KEY'] = 'some really really secret key'
    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///db.sqlite3'
    #app.config['MAIL_SERVER'] = 'smtp.gmail.com' #While commented this is localhost
    app.config['MAIL_PORT'] = 465
    app.config['MAIL_USE_TLS'] = True
    app.config['MAIL_USERNAME'] = email
    app.config['MAIL_PASSWORD'] = password
    app.config['MAIL_DEFAULT_SENDER'] = email
    
    #Initiate database
    db.init_app(app)

    #create database
    def create_db(app):
        if not os.path.exists('db.sqlite3'):
            return  db.create_all(app=app) 

    create_db(app)

    #Initiate email functions
    mail.init_app(app)

    #Blueprints register
    from .store import store
    from .auth import auth
    app.register_blueprint(store, url_prefix='/')
    app.register_blueprint(auth,url_prefix='/')

    #Set Up Login Manager
    login_manager = LoginManager()
    login_manager.login_view = 'auth.login' 
    login_manager.init_app(app)
    
    from .models import User
    #Important!
    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))


    return app

ecommerce/auth.py
from flask import flash, request, redirect, Blueprint, url_for
from . import db, views, models, store
from .models import User 
from werkzeug.security import check_password_hash, generate_password_hash
from flask_login import login_user, logout_user, current_user, login_required 
import logging


#Set up logger
logger = logging.getLogger(__name__)
logger.setLevel(logging.DEBUG)
logging.basicConfig(filename='server.log', format='%(asctime)s:%(module)s:%(levelname)s:%(message)s')

#Set up Blueprint
auth = Blueprint('auth', __name__)


@auth.route('/register', methods=['GET','POST'])
def register():
    if request.method == 'POST':
        #variables
        username = request.form.get('username') 
        passwd = request.form.get('pass') 
        passwd_conf = request.form.get('conf-pass') 
        email = request.form.get('email') 
        abc = 'qwertyuiopasdfghjklzxcvbnm'
        num = '0123456789'
        
        def is_symbol(character):
            if character not in abc and character not in num:
                return True

        #validation
        if len(username) < 3:
            flash('Your username is too short', category='error')
        elif len(username) > 30:
            flash('Your username is too long',category='error')
        elif len(passwd) < 8:
            flash('Your password is too short',category='error')
        elif len(passwd) > 30:
            flash('Your password is too long', category='error')
        elif not any(i in passwd for i in num):
            flash('Your password should be alphanumeric, but it has no numbers', category='error')
        elif not any(i in passwd for i in abc):
            flash('Your password should be alphanumeric, but it has no lowercase letters',category='error')
        elif not any(i in passwd for i in abc.upper()):
            flash('Your passoword have not uppercase letters', category='error')
        elif not any(is_symbol(i) for i in passwd):
            flash('Your password should have at least one symbol', category='error')
        elif '@' not in email or '.' not in email:
            flash('This email, seems not legit...', category='error')
        #add new user to db
        else:
            new_user = User(username=username, password=generate_password_hash(passwd, method='sha256'), email=email)
            db.session.add(new_user)
            db.session.commit()
            flash('Congratulations! You are registered, now you can start to buy!', category='success')
            login_user(new_user, remember=True)
    return views.register()

@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        #variables
        passwd = request.form.get('pass')
        login = request.form.get('login')
        try:
                    #SqlAlchemy stuff
            user = User.query.filter_by(username=login).first()
        except:
            user = User.query.filter_by(email=login).first()

        if user:
            if check_password_hash(user.password, passwd):
                flash('Logged in succesfully!', category='success')
                login_user(user, remember=True)
                return redirect(url_for('store.index'))
            else:
                flash('Incorrect password', category='error')
        else:
            flash('User does not exist', category='error')
    return views.login()

#criar pagina, procurar uma api que de conta da compra e o bootstrap acho que tem um apagina de cart


@auth.route('/new_password', methods=['GET', 'POST'])
def new_password():
    return views.new_password()


#Colocar botao para logout em algum lugar
@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('store.index'))

ecommerce/views.py
from flask import render_template

def index():
    return render_template('index.html')

def collection():
    return render_template('collection.html')

def contact():
    return render_template('contact.html')

def racing_boots():
    return render_template('racing_boots.html')

def shoes():
    return render_template('shoes.html')

def register():
    return render_template('register.html')

def login():
    return render_template('login.html')

def new_password():
    return render_template('new_password.html')

ecommerce/templates/base.html
<!DOCTYPE html>
<html lang="en">
   <head>
      <!-- basic -->
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <!-- mobile metas -->
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta name="viewport" content="initial-scale=1, maximum-scale=1">
      <!-- site metas -->
      <title>Pullshoes</title>
      <meta name="keywords" content="">
      <meta name="description" content="">
      <meta name="author" content="">
      <!-- bootstrap css -->
      <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
      <!-- style css -->
      <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
      <!-- Responsive-->
      <link rel="stylesheet" href="{{ url_for('static', filename='css/responsive.css') }}">
      <!-- fevicon -->
      <link rel="icon" href="{{ url_for('static', filename='images/fevicon.png') }}" type="image/gif" />
      <!-- Scrollbar Custom CSS -->
      <link rel="stylesheet" href="{{ url_for('static', filename='css/jquery.mCustomScrollbar.min.css') }}">
      <!-- Tweaks for older IEs-->
      <link rel="stylesheet" href="{{ url_for('static', filename='https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css') }}">
      <!-- owl stylesheets --> 
      <link rel="stylesheet" href="{{ url_for('static', filename='css/owl.carousel.min.css') }}"> 
      <link rel="stylesheet" href="{{ url_for('static', filename='css/owl.theme.default.min.css') }}"> 
      <link rel="stylesheet" href="{{ url_for('static', filename='https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css') }}" media="screen">
      <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
   </head>
   <!-- body -->
   <body class="main-layout">
	<!-- header section start -->     	<div class="header_section">
		<div class="container">
			<div class="row">
				<div class="col-sm-3">
					<div class="logo"><a href="{{ url_for('store.index') }}"><img src="{{ url_for('static', filename='images/logo.png') }}"></a></div>
				</div>
				<div class="col-sm-9">
					<nav class="navbar navbar-expand-lg navbar-light bg-light">
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                        </button>
                    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                        <div class="navbar-nav">
                           <a class="nav-item nav-link" href="{{ url_for('store.index', _external=True) }}">Home</a>
                           <a class="nav-item nav-link" href="{{ url_for('store.collection', _external=True) }}">Collection</a>
													 <a class="nav-item nav-link" href="{{ url_for('store.shoes', _external=True) }}">Shoes</a>
                           <a class="nav-item nav-link" href="{{ url_for('store.racing_boots', _external=True) }}">Racing Boots</a>
                           <a class="nav-item nav-link" href="{{ url_for('store.contact', _external=True) }}">Contact</a>
                           <a class="nav-item nav-link last" href="{{ url_for('store.index', _external=True) }}"><img src="{{ url_for('static', filename='images/shop_icon.png') }}
"></a>
                           {% if current_user.is_authenticated %} 
                            <a class="nav-item nav-link last" href="{{ url_for('auth.logout', _external=True) }}"><button class="btn btn-outline-danger">Logout</button></a>
                            {% else %}
                            <a class="nav-item nav-link last" href="{{ url_for('auth.login', _external=True) }}"><button class="btn btn-outline-primary">Login</button></a>
                            {% endif %}
                        </div>
                    </div>               
          </nav>
          <!--search bar-->
          <input class="bg-dark" style='border-radius:20%;' type="text" placeholder='Search'>
				</div>
			</div>
		</div>
	<!-- header section end -->
  {% block body %}  {% endblock %}

	<!-- section footer start -->
    <div class="section_footer">
    	<div class="container">
    		<div class="mail_section">
    			<div class="row">
    				<div class="col-sm-6 col-lg-2">
    					<div><a href="#"><img src="{{ url_for('static', filename='images/footer-logo.png') }}"></a></div>
    				</div>
    				<div class="col-sm-6 col-lg-2">
    					<div class="footer-logo"><img src="{{ url_for('static', filename='images/phone-icon.png') }}"><span class="map_text">(71) 1234567890</span></div>
    				</div>
    				<div class="col-sm-6 col-lg-3">
    					<div class="footer-logo"><img src="{{ url_for('static', filename='images/email-icon.png') }}"><span class="map_text">Demo@gmail.com</span></div>
    				</div>
    				<div class="col-sm-6 col-lg-3">
    					<div class="social_icon">
    						<ul>
    							<li><a href="#"><img src="{{ url_for('static', filename='images/fb-icon.png') }}"></a></li>
    							<li><a href="#"><img src="{{ url_for('static', filename='images/twitter-icon.png') }}"></a></li>
    							<li><a href="#"><img src="{{ url_for('static', filename='images/in-icon.png') }}"></a></li>
    							<li><a href="#"><img src="{{ url_for('static', filename='images/google-icon.png') }}"></a></li>
    						</ul>
    					</div>
    				</div>
    				<div class="col-sm-2"></div>
    			</div>
    	    </div> 
    	    <div class="footer_section_2">
		        <div class="row">
    		        <div class="col-sm-4 col-lg-2">
    		        	<p class="dummy_text"> ipsum dolor sit amet, consectetur ipsum dolor sit amet, consectetur  ipsum dolor sit amet,</p>
    		        </div>
    		        <div class="col-sm-4 col-lg-2">
    		        	<h2 class="shop_text">Address </h2>
    		        	<div class="image-icon"><img src="{{ url_for('static', filename='images/map-icon.png') }}"><span class="pet_text">No 40 Baria Sreet 15/2 NewYork City, NY, United States.</span></div>
    		        </div>
    		        <div class="col-sm-4 col-md-6 col-lg-3">
    				    <h2 class="shop_text">Our Company </h2>
    				    <div class="delivery_text">
    				    	<ul>
    				    		<li>Delivery</li>
    				    		<li>Legal Notice</li>
    				    		<li>About us</li>
    				    		<li>Secure payment</li>
    				    		<li>Contact us</li>
    				    	</ul>
    				    </div>
    		        </div>
    			<div class="col-sm-6 col-lg-3">
    				<h2 class="adderess_text">Products</h2>
    				<div class="delivery_text">
    				    	<ul>
    				    		<li>Prices drop</li>
    				    		<li>New products</li>
    				    		<li>Best sales</li>
    				    		<li>Contact us</li>
    				    		<li>Sitemap</li>
    				    	</ul>
    				    </div>
    			</div>
    			<div class="col-sm-6 col-lg-2">
    				<h2 class="adderess_text">Newsletter</h2>
    				<div class="form-group">
                        <input type="text" class="enter_email" placeholder="Enter Your email" name="Name">
                    </div>
                    <button class="subscribr_bt">Subscribe</button>
    			</div>
    			</div>
    	        </div> 
	        </div>
    </div>
	<!-- section footer end -->
	<div class="copyright">2019 All Rights Reserved. <a href="{{ 'https://html.design' }}">Free html  Templates</a></div>


      <!-- Javascript files-->
      <script src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
      <script src="{{ url_for('static', filename='js/popper.min.js') }}"></script>
      <script src="{{ url_for('static', filename='js/bootstrap.bundle.min.js') }}"></script>
      <script src="{{ url_for('static', filename='js/jquery-3.0.0.min.js') }}"></script>
      <script src="{{ url_for('static', filename='js/plugin.js') }}"></script>
      <!-- sidebar -->
      <script src="{{ url_for('static', filename='js/jquery.mCustomScrollbar.concat.min.js') }}"></script>
      <script src="{{ url_for('static', filename='js/custom.js') }}"></script>
      <!-- javascript --> 
      <script src="{{ url_for('static', filename='js/owl.carousel.js') }}"></script>
      <script src="{{ 'https:cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.js' }}"></script>
      <script>
         $(document).ready(function(){
         $(".fancybox").fancybox({
         openEffect: "none",
         closeEffect: "none"
         });
         
         
$('#myCarousel').carousel({
            interval: false
        });

        //scroll slides on swipe for touch enabled devices

        $("#myCarousel").on("touchstart", function(event){

            var yClick = event.originalEvent.touches[0].pageY;
            $(this).one("touchmove", function(event){

                var yMove = event.originalEvent.touches[0].pageY;
                if( Math.floor(yClick - yMove) > 1 ){
                    $(".carousel").carousel('next');
                }
                else if( Math.floor(yClick - yMove) < -1 ){
                    $(".carousel").carousel('prev');
                }
            });
            $(".carousel").on("touchend", function(){
                $(this).off("touchmove");
            });
        });
      </script> 
   </body>
</html>

ecommerce/templates/collection.html
{% extends 'base.html' %}

{% block body %}
				</div>
			</div>
		</div>
	</div>
	<!-- new collection section start -->
  <div class="collection_text">Collection</div>
    <div class="layout_padding collection_section">
    	<div class="container">
    	    <h1 class="new_text"><strong>New  Collection</strong></h1>
    	    <p class="consectetur_text">consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation</p>
    	    <div class="collection_section_2">
    	    	<div class="row">
    	    		<div class="col-md-6">
    	    			<div class="about-img">
    	    				<button class="new_bt">New</button>
    	    				<div class="shoes-img"><img src="{{ url_for('static', filename='images/shoes-img1.png')}}"></div>
    	    				<p class="sport_text">Men Sports</p>
    	    				<div class="dolar_text">$<strong style="color: #f12a47;">90</strong> </div>
    	    				<div class="star_icon">
    	    					<ul>
    	    						<li><a href="#"><img src="{{ url_for('static', filename='images/star-icon.png')}}"></a></li>
    	    						<li><a href="#"><img src="{{ url_for('static', filename='images/star-icon.png')}}"></a></li>
    	    						<li><a href="#"><img src="{{ url_for('static', filename='images/star-icon.png')}}"></a></li>
    	    						<li><a href="#"><img src="{{ url_for('static', filename='images/star-icon.png')}}"></a></li>
    	    						<li><a href="#"><img src="{{ url_for('static', filename='images/star-icon.png')}}"></a></li>
    	    					</ul>
    	    				</div>
    	    			</div>
                <a href='{{ url_for('store.shoes') }}'><button class="seemore_bt">See More</button></a>
    	    		</div>
    	    		<div class="col-md-6">
    	    			<div class="about-img2">
    	    				<div class="shoes-img2"><img src="{{ url_for('static', filename='images/shoes-img2.png')}}"></div>
    	    				<p class="sport_text">Men Sports</p>
    	    				<div class="dolar_text">$<strong style="color: #f12a47;">90</strong> </div>
    	    				<div class="star_icon">
    	    					<ul>
    	    						<li><a href="#"><img src="{{ url_for('static', filename='images/star-icon.png')}}"></a></li>
    	    						<li><a href="#"><img src="{{ url_for('static', filename='images/star-icon.png')}}"></a></li>
    	    						<li><a href="#"><img src="{{ url_for('static', filename='images/star-icon.png')}}"></a></li>
    	    						<li><a href="#"><img src="{{ url_for('static', filename='images/star-icon.png')}}"></a></li>
    	    						<li><a href="#"><img src="{{ url_for('static', filename='images/star-icon.png')}}"></a></li>
    	    					</ul>
    	    				</div>
    	    			</div>
    	    		</div>
    	    	</div>
    	    </div>
    	</div>
    </div>

{% endblock %}

ecommerce/templates/contact.html
{% extends 'base.html' %}

{% block body %}
				</div>
			</div>
		</div>
	</div>
   	<!-- contact section start -->
    <div class="collection_text">Contact Us</div>
    <div class="layout_padding contact_section">
    	<div class="container">
    		<h1 class="new_text"><strong>Contact Now</strong></h1>
    	</div>
    	<div class="container-fluid ram">
    		<div class="row">
    			<div class="col-md-6">
    				<div class="email_box">
                    <div class="input_main">
                       <div class="container">
                          <form action="{{ url_for('store.contact' ) }}" method='POST'>
                            <div class="form-group">
                              <input type="text" class="email-bt" placeholder="Name" name="Name">
                            </div>
                            <div class="form-group">
                              <input type="text" class="email-bt" placeholder="Phone Number" name="Name">
                            </div>
                            <div class="form-group">
                              <input type="text" class="email-bt" placeholder="Email" name="Email">
                            </div>
                            
                            <div class="form-group">
                                <textarea class="massage-bt" placeholder="Message" rows="5" id="comment" name="Message"></textarea>
                            </div>
                       <div class="send_btn">
                        <button class="main_bt">Send</button>
                       </div>                   
                          </form>   
                       </div> 
                    </div>
    		</div>
    			</div>
    			<div class="col-md-6">
    				<div class="shop_banner">
    					<div class="our_shop">
    						<button class="out_shop_bt">Our Shop</button>
    					</div>
    				</div>
    			</div>
    		</div>
    	</div>
    </div>
   	<!-- contact section end -->
   {% endblock %}

ecommerce/templates/login.html
{% extends 'base.html' %}

{% block body %}
				</div>
			</div>
		</div>
	</div>
    <div class="collection_text mb-2">Login</div>
  <div class="layout_padding">
      <center><form class='p-3' action="{{ url_for('auth.login') }}" method='POST'>
            <input class="form-control" type="text" name='login' placeholder='Username or Email' required style="width:30%">
             <input class="form-control mt-1" type="password" name='pass' placeholder='Password' required style="width:30%">
             <br>
             <button class="btn btn-primary">Login</button>
             <div>
             {% with msgs = get_flashed_messages(with_categories=True) %}
                {% if msgs %}   
                    {% for category, msg in msgs %}
                        {% if category == 'error' %}
                        <span class="text-danger">{{ msg }}</span>
                        {% endif %}
                        {% if category == 'success' %}
                        <span class="text-success">{{ msg }}</span>
                        {% endif %}
                    {% endfor %}
                {% endif %}
             {% endwith %}
             <a href="{{ url_for('auth.register', _external=True) }}">Not registered yet? Click here</a>
             </div>
             <div>
             <a href="{{ url_for('auth.new_password', _external=True) }}"> Forgot your Password? Click here</a>
             </div>
          </form></center>
  </div>

{% endblock %}

ecommerce/templates/new_password.html
{% extends 'base.html' %}

{% block body %}
				</div>
			</div>
		</div>
	</div>
    <div class="collection_text mb-2">Change your password</div>
  <div class="layout_padding">
      <center><form class='p-3' action="{{ url_for('auth.login') }}" method='POST'>
 <input class="form-control" type="text" name='pass' placeholder='New Password' required style="width:30%">
<input class="form-control mt-1" type="text" name='conf-pass' placeholder='Confirm New Password' required style="width:30%">
     <br>
     <button class="btn btn-primary">Change</button>
      </form></center>
  </div>

{% endblock %}

ecommerce/templates/racing_boots.html
{% extends 'base.html' %}

{% block body %}
				</div>
			</div>
		</div>
	</div>
	<!-- new collection section start -->
  <div class="collection_text">Racing Boots</div>
   <div class="about_main layout_padding">
    <div class="collection_section">
    	<div class="container">
    		<h1 class="new_text"><strong>Racing Boots</strong></h1>
    	    <p class="consectetur_text">consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation</p>
    	</div>
    </div>
    <div class="collectipn_section_3 layout_padding">
    	<div class="container">
    		<div class="racing_shoes">
    			<div class="row">
    				<div class="col-md-8">
    					<div class="shoes-img3"><img src="{{ url_for('static', filename='images/shoes-img3.png')}}"></div>
    				</div>
    				<div class="col-md-4">
    					<div class="sale_text"><strong>Sale <br><span style="color: #0a0506;">JOGING</span> <br>SHOES</strong></div>
    					<div class="number_text"><strong>$ <span style="color: #0a0506">100</span></strong></div>
              <a href='{{ url_for('store.shoes') }}'>	<button class="seemore">See More</button></a>
    				</div>
    			</div>
    		</div>
    	</div>
    </div>
    </div>
	<!-- new collection section end -->
{% endblock %}

ecommerce/templates/register.html
{% extends 'base.html' %}

{% block body %}
				</div>
			</div>
		</div>
	</div>
    <div class="collection_text mb-2">Register Now!</div>
<div class="layout_padding">
    <center><form class='p-3' action="{{ url_for('auth.register') }}" method='POST'>
    <input class="form-control" type="text" name='username' placeholder='Username' required style="width:30%">
     <input class="form-control mt-1" type="text" name='email' placeholder='Email' required style="width:30%">
     <input class="form-control mt-1" type="password" name='pass' placeholder='Password' required style="width:30%" style="width:30%">
 <input class="form-control mt-1" type="password" name='conf-pass' placeholder='Confirm Password' required style="width:30%">
     <br>
     <button class="btn btn-primary">Register</button>
     {% with msgs = get_flashed_messages(with_categories=True) %}
        {% if msgs %}   
            {% for category, msg in msgs %}
                {% if category == 'error' %}
                <span class="text-danger">{{ msg }}</span>

                {% endif %}
                {% if category == 'success' %}
                <span class="text-success">{{ msg }}</span>
                {% endif %}
            {% endfor %}
        {% endif %}
     {% endwith %}
        </form></center>
</div>

{% endblock %}